version: "3.9"
services:
  invest-bot:
    container_name: invest-bot
    build:
      dockerfile: Dockerfile
    env_file:
      - invest.env
    hostname: invest.bot
    ports:
      - "8080:8080"
    networks:
      - invest-network
    depends_on:
      - postgres
  cbr_service:
    container_name: cbr_service
    image: nineisfuture/sbrservice:v03
    hostname: cbr.service
    ports:
      - "8081:8081"
    networks:
      - invest-network
  tinkoff_stocks_service:
    container_name: tinkoff_stocks_service
    image: nineisfuture/tinkoffstocks:v02
    env_file:
      - invest.env
    hostname: tinkoff.stocks.service
    ports:
      - "8083:8083"
    networks:
      - invest-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: invest_postgres
    volumes:
      - ./database-scripts/init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - invest-network

networks:
  invest-network:
    driver: bridge