bot:
  token: ${BOT_TOKEN}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    #jdbc:postgresql://localhost:5433/trainerslog
    url: jdbc:postgresql://${DB_HOST:subscribes_invest_postgres}:${DB_PORT:5432}/${DB_NAME:subscribes_invest}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver