bot:
  token: ${BOT_TOKEN}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    #jdbc:postgresql://localhost:5433/trainerslog
    #url: jdbc:postgresql://${DB_HOST:subscribes_invest_postgres}:${DB_PORT:5432}/${DB_NAME:investbot}
    url: jdbc:postgresql://localhost:5432/investbot
    username: postgres #${DB_USERNAME:postgres}
    password: 2435 #${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver