services:
  tinkoff-invest:
    url: ""
  cbr-currencies:
    url: ""
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:subscribes_invest_postgres}:${DB_PORT:5432}/${DB_NAME:investbot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
server:
  port: 8080