service:
  tinkoff-invest:
    url: "http://localhost:8082/api/tinkoff"
  cbr-currencies:
    url: "http://localhost:8081/api/cbr/currency"
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://${DB_HOST:invest.postgres}:${DB_PORT:5432}/${DB_NAME:investbot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
server:
  port: 8080